version: '2'
services:
  httpd:
    build: ./images/httpd
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./config/httpd:/config/apache"
      - "./logs/httpd:/config/log"
      - "./data:/config/www"
  sonarr:
    build: ./images/sonarr
    volumes:
      - "/dev/rtc:/dev/rtc:ro" # mono theows exception otherwise
      - "./config/sonarr:/config"
      - "./logs/sonarr:/config/logs"
      - "./data/TV:/tv"
      - "./data/work/drone-factory:/drone-factory"
      - "./data/work/nzb/complete:/downloads"
  sabnzbd:
    build: ./images/sabnzbd
    volumes:
      - "./config/sabnzbd:/config"
      - "./logs/sabnzbd:/config/logs"
      - "./data/work/nzb/complete:/downloads"
      - "./data/work/nzb/incomplete:/incomplete-downloads"
      - "/etc/localtime:/etc/localtime:ro"
  couchpotato:
    build: ./images/couchpotato
    volumes:
      - "./config/couchpotato:/config"
      - "./logs/couchpotato:/data/logs"
      - "./data/Movies:/movies"
      - "./data/work/nzb/complete:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
