version: '2'
services:
  sonarr:
    image: linuxserver/sonarr
    volumes:
      - "/dev/rtc:/dev/rtc:ro" # mono theows exception otherwise
      - "./config/sonarr:/config"
      - "./data/TV:/tv"
      - "./data/downloads/complete:/downloads"
  httpd:
    build: ./images/httpd
    ports:
      - "80:80"
    volumes:
      - "./config/httpd:/usr/local/apache2/conf"
      - "./logs/httpd:/mnt/logs"
      - "./data:/mnt/data"
  sabnzbd:
    build: ./images/sabnzbd
    volumes:
      - "./config/sabnzbd:/mnt/config"
      - "./data:/mnt/data"
