version: '2'
services:
  httpd:
    build: ./images/httpd
    environment:
      - PUID=1000
      - GUID=1000
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./config/httpd:/config/apache"
      - "./logs/httpd:/config/log"
      - "./data:/config/www"
  sonarr:
    build: ./images/sonarr
    environment:
      - PUID=1000
      - GUID=1000
    volumes:
      - "/dev/rtc:/dev/rtc:ro" # mono theows exception otherwise
      - "./config/sonarr:/config"
      - "./data/TV:/tv"
      - "./data/downloads/complete:/downloads"
  sabnzbd:
    image: linuxserver/sabnzbd
    environment:
      - PUID=1000
      - GUID=1000
    volumes:
      - "./config/sabnzbd:/config"
      - "./data/work/nzb/complete:/downloads"
      - "./data/work/nzb/incomplete:/incomplete-downloads"
      - "/etc/localtime:/etc/localtime:ro"
